# Generated by Django 5.2.3 on 2025-07-13 04:48

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('content', models.FileField(max_length=255, upload_to='contents/%Y/%m/%d/')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KnowledgeBase',
                'verbose_name_plural': 'KnowledgeBases',
            },
        ),
    ]
